### PR TITLE
Catch invalid param exception

### PR DESCRIPTION
**Pull request by xabxx**
Description of changes:*
- potential fix for https://github.com/aws-robotics/cloudwatchlogs-ros1/issues/54

### CODE REVIEW

**Comment by xabxx** [comment]
Adding unit test for checking invalid parameter is caught.

**Comment by AAlon** [comment]
I'm worried about other errors which we're not looking for. The root cause of the issue is us cherry-picking specific errors to check against instead of classifying all non-retryable errors as such, so adding one more error to the list is not solving the big picture problem. Let's spend a bit more time to get rid of this switch block and check the HTTP status instead. Retryable errors are 5XX (server side) or 429 (throttling). Example: https://github.com/aws/aws-sdk-js/blob/v2.543.0/lib/util.js#L896

**Comment by raghaprasad** [comment]
> I'm worried about other errors which we're not looking for. The root cause of the issue is us cherry-picking specific errors to check against instead of classifying all non-retryable errors as such, so adding one more error to the list is not solving the big picture problem. Let's spend a bit more time to get rid of the switch block and check the HTTP status instead. Retryable errors are 5XX (server side) or 429 (throttling). Example: https://github.com/aws/aws-sdk-js/blob/v2.543.0/lib/util.js#L896

Is there any bearing on how we handle the exception and the logic to determine if the logs should go to the offline cache? @dabonnie 

I like @AAlon 's  recommendation, curious to know why we did not choose that option to begin with. I suspect that somehow the exception logic is intertwined with support for offline and I want to confirm that before we make further progress.

**Comment by dabonnie** [comment]
A few items:

1. How do we obtain the HTTP Status code from the C++ SDK? The only [errors](https://sdk.amazonaws.com/cpp/api/1.6.53/_cloud_watch_logs_errors_8h_source.html) I see returnable by [PutLogEvents](https://sdk.amazonaws.com/cpp/api/1.6.53/class_aws_1_1_cloud_watch_logs_1_1_cloud_watch_logs_client.html#adc1c9359e4c91f17f9492d567b647c64) are defined as enums as part of the API. 

2. We should ensure all defined errors [here (cloudwatch)](https://sdk.amazonaws.com/cpp/api/1.6.53/_cloud_watch_logs_errors_8h_source.html) and [here (core)](https://sdk.amazonaws.com/cpp/api/1.6.53/namespace_aws_1_1_client.html#a5d0870ca2a71145bf6947fc61db5328dacb99fc6385df8cff7e69a5af5b1cec17) are handled appropriately; we may need to engage the SDK team to determine their scope. 

3. I don't see a way to avoid cherry picking errors, e.g., data should be be discarded due to throttling but it should if improperly formatted or it exceeds the size / age limit.

I see all of the above as additional issues while not blocking this patch. However, one issue that this patch does not address is that the "old" data is still stored on disk and will be attempted to be uploaded later. I think we may need a mechanism to prune the offline logs.

**Comment by AAlon** [comment]
> A few items:
> 
> 1. How do we obtain the HTTP Status code from the C++ SDK? The only [errors](https://sdk.amazonaws.com/cpp/api/1.6.53/_cloud_watch_logs_errors_8h_source.html) I see returnable by [PutLogEvents](https://sdk.amazonaws.com/cpp/api/1.6.53/class_aws_1_1_cloud_watch_logs_1_1_cloud_watch_logs_client.html#adc1c9359e4c91f17f9492d567b647c64) are defined as enums as part of the API.

The error returned is an `Aws::Client::AWSError<CloudWatchLogsErrors>` object which has methods like `GetResponseCode`, `GetResponseHeaders` (in addition to `GetErrorType` which we use).

> 2. We should ensure all defined errors [here (cloudwatch)](https://sdk.amazonaws.com/cpp/api/1.6.53/_cloud_watch_logs_errors_8h_source.html) and [here (core)](https://sdk.amazonaws.com/cpp/api/1.6.53/namespace_aws_1_1_client.html#a5d0870ca2a71145bf6947fc61db5328dacb99fc6385df8cff7e69a5af5b1cec17) are handled appropriately; we may need to engage the SDK team to determine their scope.
> 3. I don't see a way to avoid cherry picking errors, e.g., data should **not** be discarded due to throttling but it should if improperly formatted or it exceeds the size / age limit.
> 

The HTTP standard already defined which codes constitute a retryable error, we don't need to think too much. 429 and 5xx should be retried, everything else should be discarded.

> I see all of the above as additional issues while not blocking this patch. However, one issue that this patch does not address is that the "old" data is still stored on disk and will be attempted to be uploaded later. I think we may need a mechanism to prune the offline logs.

I agree that we can merge this with no downside and separately work on a follow up, but the follow up is a couple lines of code so might as well just do it...

**Comment by dabonnie** [comment]
> everything else should be discarded.

Discarded as the data should never be uploaded?

> I agree that we can merge this with no downside and separately work on a follow up, but the follow up for classifying errors correctly is a couple lines of code so might as well just do it...

If it's simple please feel free to open an issue + PR so we can merge independently while reducing the scope here :-).

It would definitely be a valuable add for both CW Logs and Metrics.

**Pull request closed without merging**
